package com.jayway.foodvoting.integrationtest;

public class RestaurantsJsonWrapper {


  public static String getRestaurantSuggestionsEndpointJSON() {
    return source();
  }

  private static String source() {

    return "{\n"
        + "    \"businesses\": [\n"
        + "        {\n"
        + "            \"id\": \"JgVDHPIlAfN0H-PHoCRzmA\",\n"
        + "            \"alias\": \"campfire-stockholm\",\n"
        + "            \"name\": \"Campfire\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/zwMBig-7Sk17uiauUqqRxg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/campfire-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 7,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"buffets\",\n"
        + "                    \"title\": \"Buffets\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegetarian\",\n"
        + "                    \"title\": \"Vegetarian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3313,\n"
        + "                \"longitude\": 18.0655429\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Brunkebergstorg 9\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 51\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Brunkebergstorg 9\",\n"
        + "                    \"111  51 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+46851726300\",\n"
        + "            \"display_phone\": \"+46 8 517 263 00\",\n"
        + "            \"distance\": 152.76811871628274\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"BuxywlnvODwSlvIJqD6APg\",\n"
        + "            \"alias\": \"klara-soppteater-stockholm\",\n"
        + "            \"name\": \"Klara Soppteater\",\n"
        + "            \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/iJ9yN3oWhoeiAS4NnfDHUg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/klara-soppteater-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 3,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"theater\",\n"
        + "                    \"title\": \"Performing Arts\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegetarian\",\n"
        + "                    \"title\": \"Vegetarian\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"soup\",\n"
        + "                    \"title\": \"Soup\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3317719,\n"
        + "                \"longitude\": 18.0636292\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Stockholms stadsteater\",\n"
        + "                \"address2\": \"Drottninggatan 34\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 51\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Stockholms stadsteater\",\n"
        + "                    \"Drottninggatan 34\",\n"
        + "                    \"111  51 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 91.70389999848452\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"vMjlF_9heCx8YH9cyvqPBA\",\n"
        + "            \"alias\": \"sally-voltaire-och-systrar-stockholm\",\n"
        + "            \"name\": \"Sally Voltaire & Systrar\",\n"
        + "            \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/Z8h7J_yyiIH26qPsjl3BGQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/sally-voltaire-och-systrar-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 12,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"coffee\",\n"
        + "                    \"title\": \"Coffee & Tea\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"raw_food\",\n"
        + "                    \"title\": \"Live/Raw Food\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"spiritual_shop\",\n"
        + "                    \"title\": \"Spiritual Shop\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3324720495687,\n"
        + "                \"longitude\": 18.0622690916061\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Plan 2, Åhlens City\",\n"
        + "                \"address2\": \"Drottninggatan 45\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 21\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Plan 2, Åhlens City\",\n"
        + "                    \"Drottninggatan 45\",\n"
        + "                    \"111  21 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468201990\",\n"
        + "            \"display_phone\": \"+46 8 20 19 90\",\n"
        + "            \"distance\": 162.7733150883454\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"vdDHbWcrkeJbZzpDXsyTlA\",\n"
        + "            \"alias\": \"waipo-stockholm\",\n"
        + "            \"name\": \"Waipo\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/-NRDWb6SaBMv1yasO4Zqqg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/waipo-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 49,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"asianfusion\",\n"
        + "                    \"title\": \"Asian Fusion\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"tapas\",\n"
        + "                    \"title\": \"Tapas Bars\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"bars\",\n"
        + "                    \"title\": \"Bars\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.33471,\n"
        + "                \"longitude\": 18.06924\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Jakobsbergsgatan 15\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 51\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Jakobsbergsgatan 15\",\n"
        + "                    \"111  51 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468211301\",\n"
        + "            \"display_phone\": \"+46 8 21 13 01\",\n"
        + "            \"distance\": 127.91992243257256\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"PM-x-h8vw0IR0qHDHmPyJQ\",\n"
        + "            \"alias\": \"at-six-stockholm\",\n"
        + "            \"name\": \"At Six\",\n"
        + "            \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/deaUqFQQf1QKDpiaKsnrEQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/at-six-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 12,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"hotels\",\n"
        + "                    \"title\": \"Hotels\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"restaurants\",\n"
        + "                    \"title\": \"Restaurants\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"bars\",\n"
        + "                    \"title\": \"Bars\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.33083,\n"
        + "                \"longitude\": 18.06702\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Brunkebergstorg 6\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 51\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Brunkebergstorg 6\",\n"
        + "                    \"111  51 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 235.284182252295\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"3BKbdylLPLa_q1bkST0vXg\",\n"
        + "            \"alias\": \"nooshi-stockholm\",\n"
        + "            \"name\": \"Nooshi\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/TRtFseGfI8gnOTr5QzOM-A/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/nooshi-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 19,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"japanese\",\n"
        + "                    \"title\": \"Japanese\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"thai\",\n"
        + "                    \"title\": \"Thai\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"chinese\",\n"
        + "                    \"title\": \"Chinese\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3322195,\n"
        + "                \"longitude\": 18.0654763\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Sergels Torg 3\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 57\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Sergels Torg 3\",\n"
        + "                    \"111  57 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468352520\",\n"
        + "            \"display_phone\": \"+46 8 35 25 20\",\n"
        + "            \"distance\": 196.21689840455107\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"ZldiYfzL4G0ewueck3yetw\",\n"
        + "            \"alias\": \"the-market-stockholm\",\n"
        + "            \"name\": \"The Market\",\n"
        + "            \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/6knkGsByzYPHpvijsb53fQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/the-market-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 1,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"scandinavian\",\n"
        + "                    \"title\": \"Scandinavian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3312194267994,\n"
        + "                \"longitude\": 18.0592114693103\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"112 26\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"112  26 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 209.93174818422813\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"pifL8b1xswdsrZC1VpMZPw\",\n"
        + "            \"alias\": \"bistro-bestick-stockholm\",\n"
        + "            \"name\": \"Bistro Bestick\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/zlpGNKeXWDxu15tCWE5qxg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/bistro-bestick-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 66,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"scandinavian\",\n"
        + "                    \"title\": \"Scandinavian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3331757,\n"
        + "                \"longitude\": 18.0594959\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Bryggargatan 8\",\n"
        + "                \"address2\": null,\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 21\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Bryggargatan 8\",\n"
        + "                    \"111  21 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468203120\",\n"
        + "            \"display_phone\": \"+46 8 20 31 20\",\n"
        + "            \"distance\": 298.35599579397325\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"dWDvpR7oYvwAbjNZYD4grw\",\n"
        + "            \"alias\": \"espresso-house-stockholm-34\",\n"
        + "            \"name\": \"Espresso House\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/IEda9FzB3_0V1_ZcnxYC8A/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/espresso-house-stockholm-34?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 9,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"cafes\",\n"
        + "                    \"title\": \"Cafes\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"coffee\",\n"
        + "                    \"title\": \"Coffee & Tea\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3301412,\n"
        + "                \"longitude\": 18.0652412\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Drottninggatan 18\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 51\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Drottninggatan 18\",\n"
        + "                    \"111  51 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+46105101274\",\n"
        + "            \"display_phone\": \"+46 10 510 12 74\",\n"
        + "            \"distance\": 166.5880749879059\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"tIT_TGhpYlwYfVO01vyNlA\",\n"
        + "            \"alias\": \"eat-out-stockholm\",\n"
        + "            \"name\": \"Eat Out\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/TiVAvmn16OBqpvDxyextKg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/eat-out-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 1,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"indpak\",\n"
        + "                    \"title\": \"Indian\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"foodtrucks\",\n"
        + "                    \"title\": \"Food Trucks\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegan\",\n"
        + "                    \"title\": \"Vegan\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": null,\n"
        + "                \"longitude\": null\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 461.55871460053964\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"gc6xI9jBbRtgmbyfq1551Q\",\n"
        + "            \"alias\": \"pong-stockholm-4\",\n"
        + "            \"name\": \"Pong\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/WpXBBFtsFWqAkvcc8a7Onw/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/pong-stockholm-4?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 24,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"asianfusion\",\n"
        + "                    \"title\": \"Asian Fusion\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"buffets\",\n"
        + "                    \"title\": \"Buffets\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"sushi\",\n"
        + "                    \"title\": \"Sushi Bars\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.33023,\n"
        + "                \"longitude\": 18.06402\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Klara Tvärgränd 3\",\n"
        + "                \"address2\": null,\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 52\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Klara Tvärgränd 3\",\n"
        + "                    \"111  52 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+4684400208\",\n"
        + "            \"display_phone\": \"+46 8 440 02 08\",\n"
        + "            \"distance\": 84.67901299233426\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"_He-V6J8LRiV3aFdXn7mAw\",\n"
        + "            \"alias\": \"zócalo-stockholm-5\",\n"
        + "            \"name\": \"Zócalo\",\n"
        + "            \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/8pSC8jMA2sN_9BPywVOzvQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/z%C3%B3calo-stockholm-5?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 18,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"mexican\",\n"
        + "                    \"title\": \"Mexican\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3319738,\n"
        + "                \"longitude\": 18.0621891\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Klarabergsgatan 29\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 21\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Klarabergsgatan 29\",\n"
        + "                    \"111  21 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+46840911507\",\n"
        + "            \"display_phone\": \"+46 8 409 115 07\",\n"
        + "            \"distance\": 110.94429261236579\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"xYQi_JDK1kTd3gjEOH3MxQ\",\n"
        + "            \"alias\": \"huaxia-supermarket-stockholm\",\n"
        + "            \"name\": \"Huaxia Supermarket\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/iY6PFlbUCsZdwD8cFwwBxA/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/huaxia-supermarket-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 1,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"grocery\",\n"
        + "                    \"title\": \"Grocery\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"homedecor\",\n"
        + "                    \"title\": \"Home Decor\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegetarian\",\n"
        + "                    \"title\": \"Vegetarian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3304405,\n"
        + "                \"longitude\": 18.0657196\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Herkulesgatan 7\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 52\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Herkulesgatan 7\",\n"
        + "                    \"111  52 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468205180\",\n"
        + "            \"display_phone\": \"+46 8 20 51 80\",\n"
        + "            \"distance\": 173.62796665958385\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"u3O5iv2rjOHM32na20AC2g\",\n"
        + "            \"alias\": \"ellis-falafel-stockholm\",\n"
        + "            \"name\": \"Elli's Falafel\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/QiNBJyjKofOpd3VfBU88rw/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/ellis-falafel-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 1,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"foodtrucks\",\n"
        + "                    \"title\": \"Food Trucks\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"falafel\",\n"
        + "                    \"title\": \"Falafel\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegetarian\",\n"
        + "                    \"title\": \"Vegetarian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.33233,\n"
        + "                \"longitude\": 18.06293\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 461.55871460053964\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"QGaf4XxdfoPh2D6Sml8fZw\",\n"
        + "            \"alias\": \"teaterbaren-stockholm\",\n"
        + "            \"name\": \"Teaterbaren\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/u2Q4UTqQTQdZ69_I2otayQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/teaterbaren-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 6,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"scandinavian\",\n"
        + "                    \"title\": \"Scandinavian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3320198,\n"
        + "                \"longitude\": 18.0641708\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Sergels Torg\",\n"
        + "                \"address2\": null,\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"103 21\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Sergels Torg\",\n"
        + "                    \"103  21 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468145606\",\n"
        + "            \"display_phone\": \"+46 8 14 56 06\",\n"
        + "            \"distance\": 323.404344203462\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"dNaOKHV8mINlg9y5gvcl-w\",\n"
        + "            \"alias\": \"belgobaren-stockholm\",\n"
        + "            \"name\": \"Belgobaren\",\n"
        + "            \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/2thjNMU45k919aDU81qgag/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/belgobaren-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 38,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"belgian\",\n"
        + "                    \"title\": \"Belgian\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"pubs\",\n"
        + "                    \"title\": \"Pubs\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 3.5,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.3328629,\n"
        + "                \"longitude\": 18.0583038\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Bryggargatan 12\",\n"
        + "                \"address2\": null,\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 21\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Bryggargatan 12\",\n"
        + "                    \"111  21 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468246640\",\n"
        + "            \"display_phone\": \"+46 8 24 66 40\",\n"
        + "            \"distance\": 306.25844220234063\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"VknJwb-ZGlQbxw6-Zuc_BA\",\n"
        + "            \"alias\": \"mögels-foodtruck-stockholm\",\n"
        + "            \"name\": \"Mögels foodtruck\",\n"
        + "            \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/xV1RvDwYZlE_dMYAlnecmQ/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/m%C3%B6gels-foodtruck-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 5,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"foodtrucks\",\n"
        + "                    \"title\": \"Food Trucks\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"vegan\",\n"
        + "                    \"title\": \"Vegan\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": null,\n"
        + "                \"longitude\": null\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+46733565988\",\n"
        + "            \"display_phone\": \"+46 73 356 59 88\",\n"
        + "            \"distance\": 461.55871460053964\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"aJTTqxTdwuBR8NnQtwrCPA\",\n"
        + "            \"alias\": \"bacio-stockholm-2\",\n"
        + "            \"name\": \"Bacio\",\n"
        + "            \"image_url\": \"\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/bacio-stockholm-2?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 1,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"restaurants\",\n"
        + "                    \"title\": \"Restaurants\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.33444,\n"
        + "                \"longitude\": 18.06408\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Hötorgshallen\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 57\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Hötorgshallen\",\n"
        + "                    \"111  57 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"\",\n"
        + "            \"display_phone\": \"\",\n"
        + "            \"distance\": 335.39387766139026\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"Ppn-UqU3H4ap5WBMh53iTg\",\n"
        + "            \"alias\": \"smak-stockholm\",\n"
        + "            \"name\": \"Smak\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/5N3S2szjLnU2TfBgs-9AAA/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/smak-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 45,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"tapasmallplates\",\n"
        + "                    \"title\": \"Tapas/Small Plates\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"scandinavian\",\n"
        + "                    \"title\": \"Scandinavian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.335247974561,\n"
        + "                \"longitude\": 18.0651394994\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$$$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Oxtorgsgatan 14\",\n"
        + "                \"address2\": \"\",\n"
        + "                \"address3\": \"\",\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 57\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Oxtorgsgatan 14\",\n"
        + "                    \"111  57 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468220852\",\n"
        + "            \"display_phone\": \"+46 8 22 08 52\",\n"
        + "            \"distance\": 484.49655350215716\n"
        + "        },\n"
        + "        {\n"
        + "            \"id\": \"rvCnHEs4a8ShgDaB08KsXg\",\n"
        + "            \"alias\": \"panini-stockholm\",\n"
        + "            \"name\": \"Panini\",\n"
        + "            \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/HOWcOCZznrkp7y-hVo7HGg/o.jpg\",\n"
        + "            \"is_closed\": false,\n"
        + "            \"url\": \"https://www.yelp.com/biz/panini-stockholm?adjust_creative=i4_hKuTbsESP6GuUD76z2w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=i4_hKuTbsESP6GuUD76z2w\",\n"
        + "            \"review_count\": 3,\n"
        + "            \"categories\": [\n"
        + "                {\n"
        + "                    \"alias\": \"salad\",\n"
        + "                    \"title\": \"Salad\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"sandwiches\",\n"
        + "                    \"title\": \"Sandwiches\"\n"
        + "                },\n"
        + "                {\n"
        + "                    \"alias\": \"italian\",\n"
        + "                    \"title\": \"Italian\"\n"
        + "                }\n"
        + "            ],\n"
        + "            \"rating\": 4,\n"
        + "            \"coordinates\": {\n"
        + "                \"latitude\": 59.335331,\n"
        + "                \"longitude\": 18.0622196\n"
        + "            },\n"
        + "            \"transactions\": [],\n"
        + "            \"price\": \"$\",\n"
        + "            \"location\": {\n"
        + "                \"address1\": \"Kungsgatan 44\",\n"
        + "                \"address2\": \"Kungshallen\",\n"
        + "                \"address3\": null,\n"
        + "                \"city\": \"Stockholm\",\n"
        + "                \"zip_code\": \"111 35\",\n"
        + "                \"country\": \"SE\",\n"
        + "                \"state\": \"AB\",\n"
        + "                \"display_address\": [\n"
        + "                    \"Kungsgatan 44\",\n"
        + "                    \"Kungshallen\",\n"
        + "                    \"111  35 Stockholm\",\n"
        + "                    \"Sweden\"\n"
        + "                ]\n"
        + "            },\n"
        + "            \"phone\": \"+468245058\",\n"
        + "            \"display_phone\": \"+46 8 24 50 58\",\n"
        + "            \"distance\": 484.04172091899534\n"
        + "        }\n"
        + "    ],\n"
        + "    \"total\": 30,\n"
        + "    \"region\": {\n"
        + "        \"center\": {\n"
        + "            \"longitude\": 18.062896728515625,\n"
        + "            \"latitude\": 59.33104362714129\n"
        + "        }\n"
        + "    }\n"
        + "}";
  }
}
